# Generated by Django 4.1 on 2023-12-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('prf_id', models.CharField(max_length=10, verbose_name='공연 번호')),
                ('prf_changed_name', models.CharField(max_length=20, verbose_name='공연 변경 제목')),
                ('prf_number', models.SmallIntegerField(verbose_name='공연 회차')),
                ('prf_time', models.CharField(max_length=10, verbose_name='공연 시간')),
                ('prf_actors', models.TextField(null=True, verbose_name='관계자 명단')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('play_id', models.CharField(max_length=5, unique=True, verbose_name='작품ID')),
                ('play_type', models.BooleanField(verbose_name='작품 종류')),
                ('play_name', models.CharField(max_length=20, unique=True, verbose_name='작품명')),
                ('play_license', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('theater_id', models.AutoField(primary_key=True, serialize=False, verbose_name='극장ID')),
                ('theater_name', models.CharField(max_length=20, verbose_name='극장명')),
                ('theater_address', models.CharField(max_length=50, verbose_name='극장 주소')),
                ('theater_price', models.IntegerField(verbose_name='대관료')),
                ('theater_contact', models.CharField(max_length=20, verbose_name='극장 연락처')),
                ('theater_size', models.SmallIntegerField(verbose_name='수용가능인원')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_id', models.IntegerField(verbose_name='예약 번호')),
                ('reservation_phone', models.CharField(max_length=11, verbose_name='예매자 연락처')),
                ('reservation_name', models.CharField(max_length=10, verbose_name='예매자 이름')),
                ('reservation_cnt', models.SmallIntegerField(verbose_name='예매 인원')),
                ('reservation_actors', models.TextField(verbose_name='지인 명단')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('reservation_prf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.performance')),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='prf_play_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.play'),
        ),
        migrations.AddField(
            model_name='performance',
            name='prf_theater_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.theater'),
        ),
    ]
